### ISSUE TITLE
Support read Iceberg dataset in Ray in distributed mode

### ISSUE THREAD

**Issue by jackye1995** [ray-project/deltacat#116] opened 2023-03-31 20:19 UTC
in https://github.com/ray-project/deltacat/issues/115, we added support through Arrow, but that requires data to be in memory. Instead of that, we could leverage `ray.data.read_parquet` and get data files from Iceberg, so that read is distributed.

**Comment by jackye1995** [comment] 2023-03-31 20:44
@JonasJ-ap  I think you are already looking into the implementation, is that right?

**Comment by JonasJ-ap** [comment] 2023-04-03 01:13
I've created a demo of integrating `pyiceberg-0.3.0` and `ray.data.read_parquet` here: https://github.com/JonasJ-ap/icebergray/blob/ce621891d52fa6bf1ead7afc583cb036b7883f35/icebergray/read_api.py

I did some tests on iceberg table containing various primitive and nested data types. It looks like iceberg works with ray's Parquet Datasource well. 

I think the remaining questions will be:
1. Where to put this `read_iceberg` api
2. How to make unit/integration tests on it.

Would like to receive more feedback and discussions on this topic. Thank you in advance.

**Comment by jackye1995** [comment] 2023-04-03 19:18
Thanks for having this so quickly, and very excited that this is working! 

I think it makes sense to add this to the ray.data module directly. @c21 any thoughts about this? Would this be feasible and can we get some help in reviews if we open a PR?

For the partitioning issue, we need to understand what is the implication of not having partitioning. Is is still distributed? Does it impact performance?

**Comment by c21** [comment] 2023-04-03 20:29
> any thoughts about this? Would this be feasible and can we get some help in reviews if we open a PR?

+1 to add into Ray Data directly. We can help review on this.

> For the partitioning issue, we need to understand what is the implication of not having partitioning. Is is still distributed? Does it impact performance?

The reading is still distributed if not specifying partitioning, we can start initial implementation without it.

**Comment by JonasJ-ap** [comment] 2023-04-11 00:09
I've opened a draft PR for the `read_iceberg` API here: https://github.com/ray-project/ray/pull/34236. Marked as "draft" since it is currently lack of unit tests. 

@c21 , @jackye1995  May I ask if you can give some initial feedback on the implementation and suggestions on how to test it? Thank you so much.

**Comment by pdames** [comment] 2023-06-26 23:50
Currently tracking this as a WIP extension to Ray Datasets at https://github.com/ray-project/deltacat/pull/131. We can consider this for contribution back to Ray Datasets once we have full write support in PyIceberg (to better support E2E read/write unit & integration testing) and a stable set of tests to protect against regression.

**Comment by pdames** [comment] 2023-07-20 17:25
Closing this issue out here since https://github.com/ray-project/ray/pull/34236 provides basic distributed read support into a Ray Dataset.

**Closed by pdames** 2023-07-20 17:25 UTC
